### ISSUE TITLE
Transfer repo to Jamie

### ISSUE THREAD

**Issue by siddharthkp** [siddharthkp/npm-cache-benchmark#3]
@JamieMason You've done most of the work here. I'm getting some pull requests that I would like you to review anyways.

It makes sense to make [JamieMason/npm-cache-benchmark](https://github.com/JamieMason/npm-cache-benchmark) the primary source.

I'll transfer the repo if you agree.

**Comment by JamieMason** [comment]
That's fine, thanks a lot. I can add you as a collaborator so you still have access 👍

**Comment by siddharthkp** [comment]
`JamieMason/npm-cache-benchmark already exists`

🙈 

Can you rename your folk?

**Comment by JamieMason** [comment]
it won't let me rename, maybe because it's a fork. I'll open a PR to merge my latest work in to yours, then delete my fork, which you can transfer.

**Comment by JamieMason** [comment]
hm, actually for now can you add me as a Collaborator? https://github.com/siddharthkp/npm-cache-benchmark/settings/collaboration. At work at the moment and this way I can work things out then do the transfer once it's all in sync.

Thanks a lot.

**Comment by siddharthkp** [comment]
Done!

**Comment by JamieMason** [comment]
Got it, thanks :+1:
